Pull request review for GLM-16 -> sprint_2
Per-Morten/imt4886_game_lobby pull request #2
Opened 2017-09-25 20:47 UTC by hedvik

2017-09-25 20:48 UTC, hedvik commented on api_layer/source/models/Match.js
> +            .then(matches => resolve(matches))
The database collection should be called matches and not match

2017-09-29 19:28 UTC, Per-Morten commented on api_layer/source/controllers/Matches.js
> +    api.route('/Matches/:gameToken')
By convention, we are apprentantly have routes as lowercase. i.e /matches/:gameToken

2017-09-29 19:30 UTC, Per-Morten requested changes
Minor comment, otherwise seems fine :)

2017-09-29 19:30 UTC, Per-Morten commented on api_layer/source/tests/matches/api.test.js
> +        .get('/Matches/' + t.context.matches[0].gameToken)
Also need to update this to "/matches/"

2017-09-30 13:13 UTC, Per-Morten approved these changes
Il fix this during merge.

2017-09-30 13:13 UTC, Per-Morten commented on api_layer/source/controllers/Matches.js
> +     * @api {get} /match/:gameToken Request matches with given gameToken
/matches/

2017-09-30 13:19 UTC, merged